from copy import deepcopy
from pathlib import Path

import pytest

from chipcompiler.data import create_workspace, load_workspace, refresh_workspace_config
from chipcompiler.data.parameter import Parameters, load_parameter, save_parameter
from chipcompiler.data.workspace.macro_location import (
    MACRO_LOCATION_MARKER,
    render_macro_location_tcl,
)

PLACEMENTS = [
    {"instance": "u_ram0", "x": 10.0, "y": 20.5, "orientation": "R0"},
    {"instance": "u_ram1", "x": 130, "y": 40.0, "orientation": "MY"},
]


def _create_workspace(tmp_path, minimal_ics55_pdk_factory, default_ics55_parameters, extra):
    pdk_root = minimal_ics55_pdk_factory(tmp_path / "ics55")
    rtl_path = tmp_path / "gcd.v"
    rtl_path.write_text("module gcd(input clk, output y); assign y = clk; endmodule\n")

    workspace_dir = tmp_path / "workspace"
    create_workspace(
        directory=workspace_dir,
        origin_def="",
        origin_verilog=rtl_path,
        pdk="ics55",
        parameters={**deepcopy(default_ics55_parameters), **extra},
        pdk_root=pdk_root,
    )
    return workspace_dir


def test_render_macro_location_tcl():
    assert render_macro_location_tcl(PLACEMENTS) == (
        f"{MACRO_LOCATION_MARKER}\n"
        "\n"
        "placeInstance u_ram0 10 20.5 R0\n"
        "setInstancePlacementStatus -status fixed -name u_ram0\n"
        "placeInstance u_ram1 130 40 MY\n"
        "setInstancePlacementStatus -status fixed -name u_ram1\n"
    )


def test_create_workspace_materializes_macro_location_tcl(
    tmp_path, minimal_ics55_pdk_factory, default_ics55_parameters
):
    workspace_dir = _create_workspace(
        tmp_path,
        minimal_ics55_pdk_factory,
        default_ics55_parameters,
        {"macro": {"placements": deepcopy(PLACEMENTS)}},
    )

    tcl = workspace_dir / "config" / "macro_location.tcl"
    assert tcl.read_text() == render_macro_location_tcl(PLACEMENTS)


def test_refresh_leaves_macro_location_untouched_without_placements(
    tmp_path, minimal_ics55_pdk_factory, default_ics55_parameters
):
    workspace_dir = _create_workspace(
        tmp_path, minimal_ics55_pdk_factory, default_ics55_parameters, {}
    )
    tcl = workspace_dir / "config" / "macro_location.tcl"
    handwritten = (
        "# Hard-macro placement commands generated by saveMacroTCL().\nplaceInstance u0 1 2 R0\n"
    )
    tcl.write_text(handwritten)

    workspace = load_workspace(workspace_dir)
    refresh_workspace_config(workspace)

    assert tcl.read_text() == handwritten


def test_refresh_rejects_invalid_placement_and_preserves_file(
    tmp_path, minimal_ics55_pdk_factory, default_ics55_parameters
):
    workspace_dir = _create_workspace(
        tmp_path, minimal_ics55_pdk_factory, default_ics55_parameters, {}
    )
    workspace = load_workspace(workspace_dir)
    tcl = Path(workspace.config["macro_location"])
    seeded = tcl.read_text()

    data = dict(workspace.parameters.data)
    data["macro"] = {"placements": [{"instance": "u0", "x": 0, "y": 0, "orientation": "r0"}]}
    workspace.parameters.data = data
    assert save_parameter(workspace.parameters)

    with pytest.raises(ValueError, match="orientation"):
        refresh_workspace_config(workspace)

    assert tcl.read_text() == seeded


def test_legacy_macro_localtion_filename_migrates_on_load(
    tmp_path, minimal_ics55_pdk_factory, default_ics55_parameters
):
    workspace_dir = _create_workspace(
        tmp_path, minimal_ics55_pdk_factory, default_ics55_parameters, {}
    )
    legacy = workspace_dir / "config" / "macro_localtion.tcl"
    canonical = workspace_dir / "config" / "macro_location.tcl"
    legacy_content = "# legacy handoff\nplaceInstance u0 1 2 R0\n"
    canonical.unlink()
    legacy.write_text(legacy_content)

    workspace = load_workspace(workspace_dir)

    assert not legacy.exists()
    assert workspace.config["macro_location"] == canonical
    assert canonical.read_text() == legacy_content


def test_macro_placements_round_trip_through_params_toml(tmp_path):
    parameters_path = tmp_path / "params.toml"
    data = {"design": "gcd", "macro": {"placements": deepcopy(PLACEMENTS)}}
    assert save_parameter(Parameters(path=parameters_path, data=deepcopy(data)))

    assert load_parameter(parameters_path).data == data
