default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff lint
        entry: uv run --no-sync ruff check
        language: system
        types_or:
          - python
          - pyi
        stages:
          - pre-commit
      - id: ruff-format
        name: Ruff format
        entry: uv run --no-sync ruff format
        language: system
        types_or:
          - python
          - pyi
        stages:
          - pre-commit

      - id: conventional-pre-commit
        name: Check commit message format
        entry: uv run --no-sync conventional-pre-commit
        language: system
        stages:
          - commit-msg
        args:
          - --verbose
          - feat
          - fix
          - docs
          - style
          - refactor
          - perf
          - test
          - build
          - ci
          - chore
          - revert
