#!/usr/bin/env python
import os
import stat
from contextlib import suppress

from rosettakit import tcl

from chipcompiler.data import Workspace, WorkspaceStep
from chipcompiler.utility import json_read


def _abspath(path: str) -> str:
    """Convert path to absolute path, handling empty strings."""
    if not path:
        return ""
    return os.path.abspath(path)


def _existing_unique_paths(paths: list[str]) -> list[str]:
    """Return existing paths in input order without duplicates."""
    unique_paths = []
    seen = set()

    for path in paths:
        if not path or not os.path.isfile(path):
            continue
        abs_path = os.path.abspath(path)
        if abs_path in seen:
            continue
        unique_paths.append(abs_path)
        seen.add(abs_path)

    return unique_paths


def _workspace_libs(workspace: Workspace) -> list[str]:
    """Read extra liberty files from the workspace DB config."""
    db_config = json_read(workspace.config.get("db", ""))
    lib_paths = db_config.get("INPUT", {}).get("lib_path", [])
    if isinstance(lib_paths, str):
        lib_paths = [lib_paths]
    if not isinstance(lib_paths, list):
        return []

    return _existing_unique_paths(lib_paths)


def generate_global_var_tcl(workspace: Workspace,
                           step: WorkspaceStep) -> str:
    """Generate global_var.tcl content dynamically from workspace configuration."""
    if not workspace.design.top_module:
        raise ValueError("TOP_NAME (workspace.design.top_module) not set")

    freq_mhz = workspace.parameters.data.get("Frequency max [MHz]")
    if freq_mhz is None:
        raise ValueError("CLK_FREQ_MHZ (Frequency max [MHz]) not set")
    if not isinstance(freq_mhz, (int, float)) or freq_mhz <= 0:
        raise ValueError(f"CLK_FREQ_MHZ must be positive number, got {freq_mhz}")

    rtl_file = step.input.get("verilog", "")
    filelist = (
        workspace.design.input_filelist
        if workspace.design.input_filelist
        else workspace.parameters.data.get("File list", "")
    )

    # Prefer filelist if available, otherwise use rtl_file --- IGNORE ---
    has_valid_filelist = filelist and os.path.exists(filelist)
    has_valid_rtl = rtl_file and os.path.exists(rtl_file)

    if not has_valid_filelist and not has_valid_rtl:
        raise ValueError(f"Neither RTL_FILE ({rtl_file}) nor filelist ({filelist}) exists")

    top_design = workspace.design.top_module
    clk_freq_mhz = (
        int(freq_mhz) if isinstance(freq_mhz, float) and freq_mhz.is_integer() else freq_mhz
    )

    # Convert all paths to absolute since Yosys runs in script/ subdirectory
    netlist_file = _abspath(step.output.get("verilog", ""))
    timing_cell_stat_rpt = _abspath(step.report.get("stat", ""))
    timing_cell_count_rpt = _abspath(step.report.get("check", ""))
    generic_stat_json = _abspath(step.report.get("stat", ""))
    synth_stat_json = _abspath(step.feature.get("stat", ""))
    synth_check_rpt = _abspath(step.report.get("check", ""))
    data_dir = _abspath(step.data.get("dir", ""))

    keep_hierarchy = "false"

    pdk = workspace.pdk
    dont_use_cells = pdk.dont_use if pdk.dont_use else []

    tie_low_cell = pdk.tie_low_cell if pdk.tie_low_cell else ""
    tie_low_port = pdk.tie_low_port if pdk.tie_low_port else ""
    tie_high_cell = pdk.tie_high_cell if pdk.tie_high_cell else ""
    tie_high_port = pdk.tie_high_port if pdk.tie_high_port else ""
    abc_driver_cell = pdk.abc_driver_cell if pdk.abc_driver_cell else "BUFX4H7L"
    abc_load = pdk.abc_load if pdk.abc_load else 0.015

    lib_stdcell = _existing_unique_paths(workspace.pdk.libs if workspace.pdk.libs else [])
    lib_files = _existing_unique_paths(lib_stdcell + _workspace_libs(workspace))

    script = tcl.Script()
    script.comment("Auto-generated by builder.py - DO NOT EDIT MANUALLY")
    script.comment("Generated configuration for Yosys synthesis")
    script.comment(f"Timestamp: {os.popen('date').read().strip()}")
    script.blank_line()
    script.set("top_design", tcl.word(top_design))
    script.set("clk_freq_mhz", clk_freq_mhz)
    script.blank_line()

    if has_valid_filelist:
        script.comment("RTL source files (from filelist)")
        script.set_path("filelist", _abspath(filelist))
    else:
        script.comment("RTL source files")
        script.set_list("rtl_file", [_abspath(rtl_file)])
    script.blank_line()

    script.comment("Output files")
    script.set_path("final_netlist_file", netlist_file)
    script.set_path("timing_cell_stat_rpt", timing_cell_stat_rpt)
    script.set_path("timing_cell_count_rpt", timing_cell_count_rpt)
    script.set_path("generic_stat_json", generic_stat_json)
    script.set_path("synth_stat_json", synth_stat_json)
    script.set_path("synth_check_rpt", synth_check_rpt)
    script.blank_line()

    script.comment("Synthesis options")
    script.set("keep_hierarchy", keep_hierarchy)
    script.blank_line()

    script.comment("Cell configurations")
    script.set_list("dont_use_cells", dont_use_cells)
    script.set("tie_low_cell", tcl.word(tie_low_cell))
    script.set("tie_low_port", tcl.word(tie_low_port))
    script.set("tie_high_cell", tcl.word(tie_high_cell))
    script.set("tie_high_port", tcl.word(tie_high_port))
    script.set("abc_driver_cell", tcl.word(abc_driver_cell))
    script.set("abc_load", abc_load)
    script.blank_line()

    script.comment("Library files")
    script.set_list("lib_stdcell_list", lib_stdcell)
    script.set_list("lib_list", lib_files)
    script.blank_line()

    script.comment("Working directories")
    script.set_path("tmp_dir", os.path.join(data_dir, 'tmp'))
    script.blank_line()
    script.comment("##############")
    script.blank_line()

    script.comment("Calculate clock period in picoseconds")
    script.set_expr("clk_period_ps", "1000000.0 / $clk_freq_mhz")
    script.blank_line()

    script.comment("Create directories")
    script.file_mkdir(tcl.var("tmp_dir"))
    script.set("stat_dir", tcl.call("file", "dirname", tcl.var("synth_stat_json")))
    with script.if_not(tcl.file_isdirectory(tcl.var("stat_dir"))):
        script.file_mkdir(tcl.var("stat_dir"))

    return script.build()


def build_step(workspace: Workspace,
               step_name: str,
               input_def: str,
               input_verilog: str,
               input_db : str | None = None,
               output_def: str = None,
               output_verilog: str = None,
               output_gds: str = None) -> WorkspaceStep:
    """
    Build the synthesis step in the specified workspace.

    Note: input_def is not used for synthesis, only input_verilog (RTL).
    Synthesis doesn't produce DEF; output_def points to verilog for flow compatibility.
    """
    step = WorkspaceStep()
    step.name = step_name
    step.tool = "yosys"
    step.version = "0.1"

    step.directory = f"{workspace.directory}/{step.name}_{step.tool}"

    step.input = {
        "verilog": input_verilog,
    }

    if output_verilog is None:
        output_verilog = f"{step.directory}/output/{workspace.design.name}_{step.name}.v.gz"
    if output_def is None:
        output_def = f"{step.directory}/output/{workspace.design.name}_{step.name}.def.gz"
    step.output = {
        "dir": f"{step.directory}/output",
        "def": output_def,
        "verilog": output_verilog,
        "fixed_verilog": f"{step.directory}/output/{workspace.design.name}_{step.name}_fixed.v.gz",
        "json": f"{step.directory}/output/{workspace.design.name}_{step.name}.json",
        "report": f"{step.directory}/output/{workspace.design.name}_{step.name}.rpt",
        "image": f"{step.directory}/output/{workspace.design.name}_{step.name}.png"
    }

    step.data = {
        "dir": f"{step.directory}/data",
        "tmp": f"{step.directory}/data/tmp",
    }

    step.feature = {
        "dir": f"{step.directory}/feature",
        "generic_stat": f"{step.directory}/feature/{step.name}_generic_stat.json",
        "stat": f"{step.directory}/feature/{step.name}_stat.json",
    }

    step.report = {
        "dir": f"{step.directory}/report",
        "stat": f"{step.directory}/report/{step.name}_stat.json",
        "check": f"{step.directory}/report/{step.name}_check.rpt",
    }

    step.log = {
        "dir": f"{step.directory}/log",
        "file": f"{step.directory}/log/{step.name}.log",
    }

    step.script = {
        "dir": f"{step.directory}/script",
        "main": f"{step.directory}/script/{step.name}_main.tcl",
    }

    step.analysis = {
        "dir": f"{step.directory}/analysis",
        "metrics": f"{step.directory}/analysis/{step.name}_metrics.json"
    }  
    
    # build sub flow paths and data
    step.subflow = {
        "path": f"{step.directory}/subflow.json",
        "steps": []
    }  
    
    # build checklist paths and data
    step.checklist = {
        "path": f"{step.directory}/checklist.json",
        "checklist": []
    }

    return step


def build_step_space(step: WorkspaceStep) -> None:
    """
    Create the workspace directories for the given step.
    """
    os.makedirs(step.directory, exist_ok=True)
    os.makedirs(step.output.get("dir", f"{step.directory}/output"), exist_ok=True)
    os.makedirs(step.data.get("dir", f"{step.directory}/data"), exist_ok=True)
    os.makedirs(step.data.get("tmp", f"{step.directory}/data/tmp"), exist_ok=True)
    os.makedirs(step.report.get("dir", f"{step.directory}/report"), exist_ok=True)
    os.makedirs(step.log.get("dir", f"{step.directory}/log"), exist_ok=True)
    os.makedirs(step.script.get("dir", f"{step.directory}/script"), exist_ok=True)
    os.makedirs(step.feature.get("dir", f"{step.directory}/feature"), exist_ok=True)
    os.makedirs(step.analysis.get("dir", f"{step.directory}/analysis"), exist_ok=True)


def build_step_config(workspace: Workspace,
                      step: WorkspaceStep):
    """
    Build the configuration files for the synthesis step.

    Creates the following directory structure:
    - script/ subdirectory with all prepared TCL scripts
    - data/ subdirectory with generated files
    """
    import shutil

    def _copy_writable(src: str, dst: str):
        """Copy file and ensure it's writable."""
        shutil.copy2(src, dst)
        with suppress(OSError):
            os.chmod(dst, os.stat(dst).st_mode | stat.S_IWUSR)

    current_dir = os.path.dirname(os.path.abspath(__file__))
    scripts_dir = os.path.abspath(os.path.join(current_dir, 'scripts'))

    for file in ['yosys_synthesis.tcl', 'init_tech.tcl']:
        src = os.path.join(scripts_dir, file)
        if os.path.exists(src):
            _copy_writable(src, os.path.join(step.script['dir'], file))

    abc_script = os.path.join(scripts_dir, 'abc-opt.script')
    if os.path.exists(abc_script):
        _copy_writable(abc_script, os.path.join(step.script['dir'], 'abc-opt.script'))

    configs_dir = os.path.abspath(os.path.join(current_dir, 'configs'))
    aig_file = os.path.join(configs_dir, 'lazy_man_synth_library.aig')
    if os.path.exists(aig_file):
        _copy_writable(aig_file, os.path.join(step.script['dir'], 'lazy_man_synth_library.aig'))

    try:
        tcl_content = generate_global_var_tcl(workspace, step)
        global_var_path = os.path.join(step.data['dir'], 'global_var.tcl')
        with open(global_var_path, 'w') as f:
            f.write(tcl_content)
    except (ValueError, OSError) as e:
        print(f"Error generating global_var.tcl: {e}")
        raise
    
    # build subflow json
    build_sub_flow(workspace=workspace,
                   workspace_step=step)
    
    build_checklist(workspace=workspace,
                    workspace_step=step)


def build_sub_flow(workspace : Workspace,
                   workspace_step : WorkspaceStep):
    from .subflow import YosysSubFlow
    subflow = YosysSubFlow(workspace=workspace,
                           workspace_step=workspace_step)
    
    subflow.build_sub_flow()    
    
def build_checklist(workspace : Workspace,
                    workspace_step : WorkspaceStep):
    from .checklist import YosysChecklist
    checklist = YosysChecklist(workspace=workspace,
                               workspace_step=workspace_step)
    
    checklist.build_checklist() 
        
def build_environment(workspace: Workspace,
                      step: WorkspaceStep):
    """
    Build the environment for the given step.
    """
    pass
