#!/usr/bin/env python
import os
import subprocess

from chipcompiler.data import StateEnum, Workspace, WorkspaceStep
from chipcompiler.tools.yosys.checklist import YosysChecklist
from chipcompiler.tools.yosys.metrics import build_step_metrics
from chipcompiler.tools.yosys.subflow import YosysSubFlow
from chipcompiler.tools.yosys.utility import check_slang_plugin, get_yosys_runtime


def _remove_parameter_overrides(text: str) -> str:
    """Remove Verilog parameter override blocks of the form #( ... )."""
    out = []
    i = 0
    length = len(text)

    while i < length:
        if text[i] == "#" and i + 1 < length and text[i + 1] == "(":
            depth = 0
            j = i + 1
            while j < length:
                if text[j] == "(":
                    depth += 1
                elif text[j] == ")":
                    depth -= 1
                    if depth == 0:
                        j += 1
                        break
                j += 1

            if depth == 0:
                i = j
                continue

        out.append(text[i])
        i += 1

    return "".join(out)


def _write_fixed_netlist(src_path: str, dst_path: str) -> bool:
    """Write an extra netlist with parameter override blocks removed."""
    if not src_path or not dst_path or not os.path.exists(src_path):
        return False

    with open(src_path, "r", encoding="utf-8", errors="ignore") as src:
        text = src.read()

    fixed = _remove_parameter_overrides(text)

    with open(dst_path, "w", encoding="utf-8") as dst:
        dst.write(fixed)

    return True


def run_step(workspace: Workspace,
             step: WorkspaceStep,
             ecc_module=None) -> bool:
    """
    Run the synthesis step using yosys.

    All configuration is provided via global_var.tcl (generated by builder.py).
    No environment variables are required.

    Args:
        workspace: The workspace containing design info
        step: The step workspace with paths and config
        ecc_module: Not used for yosys (kept for API compatibility)

    Returns:
        True if synthesis succeeded, False otherwise
    """
    sub_flow = YosysSubFlow(workspace=workspace, workspace_step=step)

    yosys_cmd, yosys_env = get_yosys_runtime()
    if not yosys_cmd:
        sub_flow.update_step(step_name="run yosys", state=StateEnum.Invalid)
        error_msg = "Error: yosys is not available (bundled runtime or PATH)."
        try:
            with open(step.log["file"], "w") as log_file:
                log_file.write(error_msg + "\n")
        except Exception:
            pass
        print(error_msg)
        return False

    input_verilog = step.input.get("verilog", "")
    input_filelist = workspace.design.input_filelist if workspace.design.input_filelist else ""

    # Validate that at least one of input_verilog or filelist is valid
    has_valid_verilog = input_verilog and os.path.exists(input_verilog)
    has_valid_filelist = input_filelist and os.path.exists(input_filelist)

    if not has_valid_verilog and not has_valid_filelist:
        sub_flow.update_step(step_name="run yosys", state=StateEnum.Invalid)
        print(f"Error: Neither RTL file ({input_verilog}) nor filelist ({input_filelist}) found")
        return False

    try:
        cwd_dir = step.script.get("dir", step.directory)

        cmd = yosys_cmd + ["yosys_synthesis.tcl"]

        with open(step.log["file"], "w") as log_file:
            if not check_slang_plugin(
                yosys_cmd=yosys_cmd,
                cwd_dir=cwd_dir,
                yosys_env=yosys_env,
                log_file=log_file
            ):
                sub_flow.update_step(step_name="run yosys", state=StateEnum.Invalid)
                return False

            result = subprocess.run(
                cmd,
                cwd=cwd_dir,
                env=yosys_env,
                stdout=log_file,
                stderr=subprocess.STDOUT,
            )

        if os.path.exists(step.output["verilog"]):
            sub_flow.update_step(step_name="run yosys", state=StateEnum.Success)

            fixed_netlist = step.output.get("fixed_verilog", "")
            if fixed_netlist:
                _write_fixed_netlist(step.output["verilog"], fixed_netlist)
            
            build_step_metrics(workspace=workspace, step=step)
            
            sub_flow.update_step(step_name="analysis", state=StateEnum.Success)
            
            checklist = YosysChecklist(workspace=workspace, workspace_step=step)
            checklist.check()
            
            return True
        else:
            sub_flow.update_step(step_name="run yosys", state=StateEnum.Invalid)
            
            print(
                f"Error: Output netlist not generated at {step.output['verilog']}. "
                f"yosys exit code: {result.returncode}"
            )
            return False

    except Exception as e:
        sub_flow.update_step(step_name="run yosys", state=StateEnum.Imcomplete)
        print(f"Error running yosys: {e}")
        return False
