from .common import config_param


def _place(param: str, default: object, *, type: str | None = None):
    return config_param(
        f"place.{param}", "dreamplace", (param,), default, applies="placement", type=type
    )


SCHEMAS = (
    _place("RePlAce_LOWER_PCOF", 0.95),
    _place("RePlAce_UPPER_PCOF", 1.05),
    _place("RePlAce_ref_hpwl", 350000),
    _place("RePlAce_skip_energy_flag", 0),
    _place("adjust_nctugr_area_flag", 1),
    _place("adjust_pin_area_flag", 0),
    _place("adjust_rudy_area_flag", 0),
    _place("area_adjust_stop_ratio", 0.01),
    _place("auto_adjust_bins", 1),
    _place("bndry_padding_x", 0),
    _place("bndry_padding_y", 0),
    _place("density_weight", 0.00085),
    _place("detailed_place_command", ""),
    _place("detailed_place_engine", ""),
    _place("detailed_place_flag", 0),
    _place("deterministic_flag", 1),
    _place("differentiable_timing_obj", 0),
    _place("dtype", "float32"),
    _place("dump_global_place_solution_flag", 0),
    _place("dump_legalize_solution_flag", 0),
    _place("enable_fillers", 1),
    _place("enable_net_weighting", 0),
    _place("evaluate_pl", 0),
    _place("gamma", 4),
    _place("get_congestion_map", 1),
    _place("global_place_flag", 1),
    _place(
        "global_place_stages",
        [
            {
                "Llambda_density_weight_iteration": 1,
                "Lsub_iteration": 1,
                "iteration": 1000,
                "learning_rate": 1.0,
                "learning_rate_decay": 0.99,
                "num_bins_x": 32,
                "num_bins_y": 32,
                "optimizer": "nesterov",
                "wirelength": "weighted_average",
            }
        ],
        type="json",
    ),
    _place("gp_noise_ratio", 0.0),
    _place("gpu", 0),
    _place("gpu_id", 0),
    _place("ignore_net_degree", 100),
    _place("ignore_net_weight", 1),
    _place("init_loc_perc_x", 0.5),
    _place("init_loc_perc_y", 0.5),
    _place("legalize_flag", 1),
    _place("macro_halo_x", 0.0),
    _place("macro_halo_y", 0.0),
    _place("macro_overlap_flag", 0),
    _place("macro_overlap_mult_weight", 1.0),
    _place("macro_overlap_weight", 8e-06),
    _place("macro_pin_halo_x", 0.0),
    _place("macro_pin_halo_y", 0.0),
    _place("macro_place_flag", 0),
    _place("max_net_weight", "inf"),
    _place("max_num_area_adjust", 3),
    _place("max_pin_opt_adjust_rate", 1.5),
    _place("max_route_opt_adjust_rate", 2.0),
    _place("momentum_decay_factor", 0.5),
    _place("net_weighting_scheme", "lilith"),
    _place("node_area_adjust_overflow", 0.15),
    _place("num_bins_x", 32),
    _place("num_bins_y", 32),
    _place("num_threads", 8, type="int"),
    _place("pin2pin_accumulate_weight", 0.1),
    _place("pin2pin_max_weight", 1.0),
    _place("pin2pin_min_weight", 1.0),
    _place("pin2pin_net_weighting", 0),
    _place("pin2pin_weight", 2.5e-05),
    _place("pin_area_adjust_stop_ratio", 0.05),
    _place("pin_density", 0.6),
    _place("pin_stretch_ratio", 1.414213562),
    _place("plot_flag", 0),
    _place("random_center_init_flag", 1),
    _place("random_seed", 3000),
    _place("risa_weights", 0),
    _place("route_area_adjust_stop_ratio", 0.01),
    _place("route_info_input", "default"),
    _place("route_num_bins_x", 512),
    _place("route_num_bins_y", 512),
    _place("route_opt_adjust_exponent", 2.0),
    _place("scale_factor", 1.0),
    _place("shift_factor", [0.0, 0.0], type="list[float]"),
    _place("sort_nets_by_degree", 0),
    _place("start_iter", 0),
    _place("timing_eval_flag", 0),
    _place("timing_opt_flag", 0),
    _place("two_stage_density_scaler", 1000.0),
    _place("unit_horizontal_capacity", 1.5625),
    _place("unit_pin_capacity", 0.058),
    _place("unit_vertical_capacity", 1.45),
    _place("use_bb", 0),
    _place("with_sta", 0),
)
