#!/usr/bin/env python
from pathlib import Path

from rosettakit import tcl

from chipcompiler.data import (
    AnalysisPaths,
    ChecklistState,
    LogPaths,
    OutputPaths,
    ScriptPaths,
    SubflowState,
    Workspace,
    YosysLecData,
    YosysLecInput,
    YosysLecReport,
    YosysLecStep,
)


def _derive_golden_path(gate_verilog: Path | str | None) -> Path | None:
    if not gate_verilog:
        return None
    gate = Path(gate_verilog)
    return gate.with_name(f"{gate.stem}_golden{gate.suffix or '.v'}")


def _optional_path(path: Path | str | None) -> Path | None:
    return Path(path) if path else None


def build_step(
    workspace: Workspace,
    step_name: str,
    input_def: Path | None,
    input_verilog: Path | None,
    input_db: Path | str | None = None,
    output_def: Path | None = None,
    output_verilog: Path | None = None,
    output_gds: Path | None = None,
) -> YosysLecStep:
    directory = Path(workspace.directory) / f"{step_name}_yosys_lec"
    output_dir = directory / "output"
    data_dir = directory / "data"
    report_dir = directory / "report"
    gate_verilog = _optional_path(input_verilog)
    golden_verilog = _optional_path(input_db) or _derive_golden_path(gate_verilog)

    return YosysLecStep(
        name=step_name,
        tool="yosys_lec",
        version="0.1",
        directory=directory,
        input=YosysLecInput(
            gate_verilog=gate_verilog,
            golden_verilog=golden_verilog,
            db=_optional_path(input_db),
        ),
        output=OutputPaths(
            dir=output_dir,
            json=output_dir / f"{workspace.design.name}_{step_name}_result.json",
        ),
        data=YosysLecData(dir=data_dir, config=data_dir / "lec_config.tcl"),
        report=YosysLecReport(
            dir=report_dir,
            status=report_dir / "run_lec_status.rpt",
            equiv_status=report_dir / "equiv_status.rpt",
            failed_rtlil=report_dir / "equiv_failed.il",
            failed_verilog=report_dir / "equiv_failed.v",
        ),
        log=LogPaths(
            dir=directory / "log",
            file=directory / "log" / f"{step_name}.log",
        ),
        script=ScriptPaths(
            dir=directory / "script",
            main=directory / "script" / "run_lec.tcl",
        ),
        analysis=AnalysisPaths(
            dir=directory / "analysis",
            metrics=directory / "analysis" / f"{step_name}_metrics.json",
        ),
        subflow=SubflowState(path=directory / "subflow.json", steps=[]),
        checklist=ChecklistState(path=directory / "checklist.json", checklist=[]),
    )


def build_step_space(step: YosysLecStep) -> None:
    step_directory = Path(step.directory)
    step_directory.mkdir(parents=True, exist_ok=True)
    Path(step.output.dir or step_directory / "output").mkdir(parents=True, exist_ok=True)
    Path(step.data.dir or step_directory / "data").mkdir(parents=True, exist_ok=True)
    Path(step.report.dir or step_directory / "report").mkdir(parents=True, exist_ok=True)
    Path(step.log.dir or step_directory / "log").mkdir(parents=True, exist_ok=True)
    Path(step.script.dir or step_directory / "script").mkdir(parents=True, exist_ok=True)
    Path(step.analysis.dir or step_directory / "analysis").mkdir(parents=True, exist_ok=True)


def _write_file(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def _lec_parameters(workspace: Workspace) -> dict:
    data = getattr(getattr(workspace, "parameters", None), "data", {}) or {}
    lec = data.get("LEC", {})
    return lec if isinstance(lec, dict) else {}


def _path_text(path: Path | str | None) -> str:
    return str(path) if path else ""


def build_step_config(workspace: Workspace, step: YosysLecStep) -> None:
    params = _lec_parameters(workspace)
    model_files = params.get("model_files", [])
    if isinstance(model_files, str):
        model_files = [model_files]

    blacklist = str(params.get("blacklist", "") or "")
    use_undef = bool(params.get("use_undef", False))
    liberty_files = [str(path) for path in (workspace.pdk.libs or []) if path]

    config = tcl.Script()
    config.comment("Auto-generated by yosys_lec.builder - DO NOT EDIT MANUALLY")
    config.set("top_design", tcl.word(workspace.design.top_module))
    config.set_path("golden_file", _path_text(step.input.golden_verilog))
    config.set_path("gate_file", _path_text(step.input.gate_verilog))
    config.set_path("report_dir", _path_text(step.report.dir))
    config.set_path("result_json", _path_text(step.output.json))
    config.set_path("status_file", _path_text(step.report.status))
    config.set_path("equiv_status_file", _path_text(step.report.equiv_status))
    config.set_path("failed_rtlil_file", _path_text(step.report.failed_rtlil))
    config.set_path("failed_verilog_file", _path_text(step.report.failed_verilog))
    config.set_list("liberty_files", liberty_files)
    config.set_list("model_files", [str(path) for path in model_files if path])
    config.set("blacklist_file", tcl.word(blacklist))
    config.set("use_undef", "true" if use_undef else "false")
    _write_file(step.data.config, config.build())

    script = """proc require_file {label path} {
    if {$path eq ""} {
        error "$label is empty"
    }
    if {![file exists $path]} {
        error "missing $label: $path"
    }
    if {![file readable $path]} {
        error "$label is not readable: $path"
    }
}

proc read_support_models {} {
    global liberty_files model_files
    foreach liberty_file $liberty_files {
        require_file "liberty file" $liberty_file
        yosys read_liberty -ignore_miss_func -ignore_miss_data_latch $liberty_file
    }
    foreach model_file $model_files {
        require_file "LEC model file" $model_file
        yosys read_verilog -sv $model_file
    }
}

proc normalize_design {top_design} {
    yosys hierarchy -top $top_design
    yosys proc
    yosys memory
    yosys async2sync
    yosys flatten
    yosys splitnets -ports -format __v
    yosys opt_clean -purge
}

proc build_design {stash_name top_design netlist_file} {
    read_support_models
    yosys read_verilog -sv $netlist_file
    normalize_design $top_design
    yosys design -stash $stash_name
}

proc write_failure_artifacts {reason} {
    global status_file equiv_status_file failed_rtlil_file failed_verilog_file
    set handle [open $status_file "w"]
    puts $handle "Yosys LEC did not prove equivalence."
    puts $handle ""
    puts $handle "Reason:"
    puts $handle $reason
    close $handle

    catch {yosys tee -o $equiv_status_file equiv_status}
    catch {yosys write_rtlil $failed_rtlil_file}
    catch {yosys write_verilog -noattr $failed_verilog_file}
}

proc run_equivalence {} {
    global top_design blacklist_file use_undef equiv_status_file
    yosys design -copy-from gold -as gold $top_design
    yosys design -copy-from gate -as gate $top_design
    if {$blacklist_file ne ""} {
        require_file "LEC blacklist" $blacklist_file
        yosys equiv_make -blacklist $blacklist_file gold gate equiv
    } else {
        yosys equiv_make gold gate equiv
    }
    yosys hierarchy -top equiv
    yosys opt_clean -purge

    if {$use_undef} {
        yosys equiv_simple -undef
        yosys equiv_induct -undef
    } else {
        yosys equiv_simple
        yosys equiv_induct
    }
    yosys tee -o $equiv_status_file equiv_status

    set handle [open $equiv_status_file "r"]
    set status_text [read $handle]
    close $handle
    if {![regexp {Equivalence successfully proven!} $status_text]
        && ![regexp {Found a total of 0 unproven \\$equiv cells\\.} $status_text]} {
        error "equivalence proof has unproven cells; see $equiv_status_file"
    }
}

set script_dir [file dirname [file normalize [info script]]]
source [file normalize [file join $script_dir .. data lec_config.tcl]]
file mkdir $report_dir

require_file "golden netlist" $golden_file
require_file "gate netlist" $gate_file

set result [catch {
    build_design gold $top_design $golden_file
    yosys design -reset
    build_design gate $top_design $gate_file
    yosys design -reset
    run_equivalence
} message]

if {$result != 0} {
    write_failure_artifacts $message
    exit 1
}

set handle [open $status_file "w"]
puts $handle "Yosys LEC completed with proven equivalence."
puts $handle "Golden: $golden_file"
puts $handle "Gate: $gate_file"
close $handle
"""
    _write_file(step.script.main, script)

    from chipcompiler.tools.yosys_lec.subflow import YosysLecSubFlow

    subflow = YosysLecSubFlow(workspace=workspace, workspace_step=step)
    subflow.build_sub_flow()
